### PR TITLE
Move share link from nginx.conf to nginxconfig.txt

### LINKED ISSUE #361: nginx test fails when nginxconfig.io url exceeds length limit
## Steps to reproduce
- Create a configuration whose `digitalocean.com/community/tools/nginx` URL is over 5000 characters in length.
- Import the configuration into `/etc/nginx`
- Run `nginx -t`
## Error occurs
```shell
nginx: [emerg] too long parameter "# https://..."
nginx: configuration file /etc/nginx/nginx.conf test failed        
``` 
## Workaround
Yank & delete the comment and put into `/etc/nginx/nginxconfig.io.url`.
Run `nginx -t` again, the check is successful, and the service starts correctly.

# Suggested solution
Store the URL in a separate file, similar to the workaround, instead of writing to `nginx.conf`.
https://github.com/digitalocean/nginxconfig.io/blob/2eac584166e8c5ba095322386533ddd9a0272b8b/src/nginxconfig/generators/conf/nginx.conf.js#L37

### PR DESCRIPTION
**Pull request by MrJmpl3**
## Type of Change

- **Build Scripts:** 
- **Tool Source:** Nginx configuracion and shared link 
- **Something else:** 

## What issue does this relate to?

Trying fix #361 

### What should this PR do?

Add a file nginxconfig.txt with shared link instead nginx.conf comment

### What are the acceptance criteria?

If all is correct, please add the tag 'hacktoberfest-accepted', Thanks

### CODE REVIEW

File: src/nginxconfig/generators/index.js [hunk 1]
```diff
@@ -40,6 +40,7 @@ import magentoConf from './conf/magento.conf';
 import joomlaConf from './conf/joomla.conf';
 import dockerComposeYaml from './yaml/dockerCompose.yaml';
 import dockerConf from './ext/docker';
+import shareQuery from '../util/share_query.js';
```
Comment (MattIPv4) [inline src/nginxconfig/generators/index.js:43]:
```suggestion
import shareQuery from '../util/share_query';
```
Just a tiny nitpick here, we don't need the extension for the file

File: src/nginxconfig/generators/conf/nginx.conf.js [hunk 2]
```diff
@@ -26,15 +26,13 @@ THE SOFTWARE.
...
-import shareQuery from '../../util/share_query';
 
 export default (domains, global) => {
     const config = {};
 
     // Source
     config['# Generated by nginxconfig.io'] = '';
-    const query = shareQuery(domains.map((domain, index) => [domain, index]).filter(d => d[0] !== null), global);
-    config[`# ${window.location.protocol}//${window.location.host}${window.location.pathname}${query}`] = '';
+    config['# See nginxconfig.txt to get the configuration shared link'] = '';
```
Comment (MattIPv4) [inline src/nginxconfig/generators/conf/nginx.conf.js:35]:
```suggestion
    config['# See nginxconfig.txt for the configuration share link'] = '';
```

**Review by MattIPv4 — CHANGES_REQUESTED** [review]

**Review by MattIPv4 — APPROVED** [review]
LGTM
