### PR TITLE
Set 'combined' as default log format when not using Cloudflare

### LINKED ISSUE #409: unknown log format "buffer=512k" in /etc/nginx/sites-enabled/mysite.conf
## Information

https://whatismybrowser.com/w/WCK9JR7

## Details

Open [this link](https://www.digitalocean.com/community/tools/nginx?domains.0.server.domain=mysite&domains.0.server.path=%2Fusr%2Fshare%2Fnginx%2Fhtml&domains.0.https.certType=custom&domains.0.https.sslCertificate=%2Fetc%2Fnginx%2Fssl%2Fmysite.crt&domains.0.https.sslCertificateKey=%2Fetc%2Fnginx%2Fssl%2Fmysite.key&domains.0.php.php=false&domains.0.reverseProxy.reverseProxy=true&domains.0.reverseProxy.proxyPass=http%3A%2F%2Fmysite%3A5000&domains.0.routing.index=index.html&domains.0.routing.fallbackHtml=true&domains.0.logging.errorLogLevel=error&global.https.ocspCloudflare=false&global.https.ocspGoogle=false&global.https.ocspOpenDns=false&global.nginx.user=nginx&global.nginx.pid=%2Fvar%2Frun%2Fnginx.pid&global.docker.dockerfile=true&global.docker.dockerCompose=true&global.app.lang=zhTW). You will find this:

```nginx
access_log          /var/log/nginx/access.log buffer=512k flush=1m;
```

Here is the NGINX log:

```log
2022-11-18 20:02:34 2022/11/18 12:02:34 [emerg] 1#1: unknown log format "buffer=512k" in /etc/nginx/sites-enabled/mysite.conf:15
2022-11-18 20:02:34 nginx: [emerg] unknown log format "buffer=512k" in /etc/nginx/sites-enabled/mysite.conf:15
```

### Description 

The generated `/etc/nginx/sites-available/mysite.conf` file contains a wrong format issue.

### Steps to reproduce

1. Open [this link](https://www.digitalocean.com/community/tools/nginx?domains.0.server.domain=mysite&domains.0.server.path=%2Fusr%2Fshare%2Fnginx%2Fhtml&domains.0.https.certType=custom&domains.0.https.sslCertificate=%2Fetc%2Fnginx%2Fssl%2Fmysite.crt&domains.0.https.sslCertificateKey=%2Fetc%2Fnginx%2Fssl%2Fmysite.key&domains.0.php.php=false&domains.0.reverseProxy.reverseProxy=true&domains.0.reverseProxy.proxyPass=http%3A%2F%2Fmysite%3A5000&domains.0.routing.index=index.html&domains.0.routing.fallbackHtml=true&domains.0.logging.errorLogLevel=error&global.https.ocspCloudflare=false&global.https.ocspGoogle=false&global.https.ocspOpenDns=false&global.nginx.user=nginx&global.nginx.pid=%2Fvar%2Frun%2Fnginx.pid&global.docker.dockerfile=true&global.docker.dockerCompose=true&global.app.lang=zhTW).

2. I run this in Docker.

    image

### Expected behavior

When I switch to the following, it works.

```nginx
access_log          /var/log/nginx/access.log combined buffer=512k flush=1m;
```

Docs here: http://nginx.org/en/docs/http/ngx_http_log_module.html

```txt
Syntax:	access_log path [format [buffer=size] [gzip[=level]] [flush=time] [if=condition]];
access_log off;
Default:
access_log logs/access.log combined;
Context:	http, server, location, if in location, limit_except
```

I think it's missing `format` if the `buffer` must be used.

### Screenshots

image

### PR DESCRIPTION
**Pull request by doggy8088**
This fixes #409

### CODE REVIEW

File: src/nginxconfig/util/logging.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ THE SOFTWARE.
 */
 
 export const accessLogPathDefault = '/var/log/nginx/access.log';
-export const accessLogParamsDefault = 'buffer=512k flush=1m';
+export const accessLogParamsDefault = 'combined buffer=512k flush=1m';
```
Comment (MattIPv4) [inline src/nginxconfig/util/logging.js:28]: Instead of adding it here, I think you want to add it to the `getDomainAccessLog` logic below, when the Cloudflare log format is not enabled?

Otherwise, you'll end up specifying two log formats when Cloudflare logging is enabled?

Comment (doggy8088) [reply src/nginxconfig/util/logging.js]: @MattIPv4 I think you are right. I pushed a new commit to fix this. Thanks.

**Review by MattIPv4 — APPROVED** [review]
